### ISSUE TITLE
UI bug / conflict with All in One SEO

### ISSUE THREAD

**Issue by openforfuture** [JJJ/post-type-switcher#46]
Conflict with [All in One SEO](https://github.com/awesomemotive/all-in-one-seo-pack/):

<img width="1121" alt="image" src="https://github.com/JJJ/post-type-switcher/assets/99279367/f20e5a3f-15b8-4ee6-873d-e1252c5d5a1b">

Disabling the plugin fixes the problem.

**Comment by JJJ** [comment]
Hey @openforfuture, thank you for creating this issue here!

I was able to reproduce this by decreasing the width of the browser window, so I do see what you mean.

This is a weird situation, where every plugin that adds their own column is going to contribute to the same inevitable problem.

I believe that fixing #20 means this plugin is far less-likely to cause the Title column to get shrunk down like that, so I am comfortable closing this issue as fixed (without actually changing any code specific to it).

Thank you again! 🙌
